test fix

diff --git a/.github/workflows/silabs-open-csa-pr.yaml b/.github/workflows/silabs-open-csa-pr.yaml
--- a/.github/workflows/silabs-open-csa-pr.yaml
+++ b/.github/workflows/silabs-open-csa-pr.yaml
@@ -5,6 +5,7 @@ permissions:
     pull-requests: write
 
 on:
+    push:
     workflow_run:
         workflows: ["Daily Sync of the csa branch"]
         types:
@@ -19,7 +20,6 @@ jobs:
             - uses: actions/checkout@v4
               with:
                   ref: main
-                  token: ${{secrets.WORKFLOW_TOKEN}}
 
             - name: Checkout csa
               run: |
@@ -37,18 +37,31 @@ jobs:
 
                       **PR MUST BE MERGED WITH MERGE COMMIT - ADMIN MUST ENABLE THE OPTION**
                   token: ${{secrets.GITHUB_TOKEN}}
-                  branch-token: ${{secrets.WORKFLOW_TOKEN}}
                   labels: changing-submodules-on-purpose
 
-            - name: Comment on Pull Request
-              uses: actions/github-script@v7
-              with:
-                  github-token: ${{secrets.GITHUB_TOKEN}}
-                  script: |
-                      const pr_number = context.payload.workflow_run.pull_requests[0].number;
-                      github.issues.createComment({
-                        owner: context.repo.owner,
-                        repo: context.repo.repo,
-                        issue_number: pr_number,
-                        body: "Please merge this PR using **Merge Commit**."
-                      });
+            - name: Check if PR is already closed and reopened
+              id: check_pr
+              run: |
+                  PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --head automation/update_main --json number --jq '.[0].number')
+                  if [ -z "$PR_NUMBER" ]; then
+                      echo "PR not found."
+                      exit 1
+                  fi
+                  LABELS=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json labels --jq '.labels[].name')
+                  if echo "$LABELS" | grep -q "sl-automation-triggered"; then
+                      echo "::set-output name=pr_already_closed::true"
+                  else
+                      echo "::set-output name=pr_already_closed::false"
+                  fi
+              env:
+                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+
+            - name: Close and Reopen PR
+              if: steps.check_pr.outputs.pr_already_closed == 'false'
+              run: |
+                  PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --head automation/update_main --json number --jq '.[0].number')
+                  gh pr close $PR_NUMBER --repo ${{ github.repository }}
+                  gh pr reopen $PR_NUMBER --repo ${{ github.repository }}
+                  gh pr edit $PR_NUMBER --add-label "sl-automation-triggered"
+              env:
+                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
