[SL-ONLY] Adapt the open PR automation to force trigger the CI jobs (#240)

diff --git a/.github/workflows/silabs-open-csa-pr.yaml b/.github/workflows/silabs-open-csa-pr.yaml
--- a/.github/workflows/silabs-open-csa-pr.yaml
+++ b/.github/workflows/silabs-open-csa-pr.yaml
@@ -19,7 +19,6 @@ jobs:
             - uses: actions/checkout@v4
               with:
                   ref: main
-                  token: ${{secrets.WORKFLOW_TOKEN}}
 
             - name: Checkout csa
               run: |
@@ -37,18 +36,34 @@ jobs:
 
                       **PR MUST BE MERGED WITH MERGE COMMIT - ADMIN MUST ENABLE THE OPTION**
                   token: ${{secrets.GITHUB_TOKEN}}
-                  branch-token: ${{secrets.WORKFLOW_TOKEN}}
                   labels: changing-submodules-on-purpose
 
-            - name: Comment on Pull Request
-              uses: actions/github-script@v7
-              with:
-                  github-token: ${{secrets.GITHUB_TOKEN}}
-                  script: |
-                      const pr_number = context.payload.workflow_run.pull_requests[0].number;
-                      github.issues.createComment({
-                        owner: context.repo.owner,
-                        repo: context.repo.repo,
-                        issue_number: pr_number,
-                        body: "Please merge this PR using **Merge Commit**."
-                      });
+            # The next two steps are necessary to force the CI to be executed when a PR is opened by the github-bot.
+            # The PR event isn't triggered when the bot opens the PR and as such doesn't trigger the workflows that use the event as their trigger.
+            # By closing and opening the PR, it forces the PR event to be triggered.
+            - name: Check if PR is already closed and reopened
+              id: check_pr
+              run: |
+                  PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --head automation/update_main --json number --jq '.[0].number')
+                  if [ -z "$PR_NUMBER" ]; then
+                      echo "PR not found."
+                      exit 1
+                  fi
+                  LABELS=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json labels --jq '.labels[].name')
+                  if echo "$LABELS" | grep -q "sl-automation-triggered"; then
+                      echo "pr_needs_reopen=true" >> $GITHUB_OUTPUT
+                  else
+                      echo "pr_needs_reopen=false" >> $GITHUB_OUTPUT
+                  fi
+              env:
+                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+
+            - name: Close and Reopen PR
+              if: ${{ steps.check_pr.outputs.pr_needs_reopen }}
+              run: |
+                  PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --head automation/update_main --json number --jq '.[0].number')
+                  gh pr close $PR_NUMBER --repo ${{ github.repository }}
+                  gh pr reopen $PR_NUMBER --repo ${{ github.repository }}
+                  gh pr edit $PR_NUMBER --add-label "sl-automation-triggered"
+              env:
+                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
